spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fhir_mii
    username: fhir
    password: fhir
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always

server:
  port: 8080
